env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/vue3-essential
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - src/api/tsconfig.json
    - src/web/tsconfig.node.json
    - src/web/tsconfig.json
plugins:
  - vue
rules: {}
