version: "3"
services:
  app:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PRODUCTION_DATABASE_SA_MASTER_CREDS_AVAILABLE: "true"
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-8080}:8080"
    volumes:
      - .env:/home/node/app/.env.production
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      # default user is `sa`
      MSSQL_SA_PASSWORD: "${DB_PASS}"
      TZ: "America/Whitehorse"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql/data

volumes:
  db_data:
