env:
  browser: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - api/tsconfig.json
plugins:
  - "@typescript-eslint"
rules: {}
