env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/vue3-recommended
  - standard-with-typescript
  - prettier
overrides: []
parser: "vue-eslint-parser"
parserOptions:
  ecmaVersion: latest
  extraFileExtensions:
    - .vue
  parser: "@typescript-eslint/parser"
  project:
    - web/tsconfig.node.json
    - web/tsconfig.json
  sourceType: module
plugins:
  - vue
rules: {}
